[package]
name = "ohmycine-plugin-bilibili"
version = "0.3.5"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
urlencoding = "2"
roxmltree = "0.21"
time = { version = "0.3", default-features = false, features = ["formatting", "parsing"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
