version: 2
updates:
  - package-ecosystem: npm
    directory: /plugin-sdk
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /hub
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: cargo
    directory: /plugins/official/bilibili
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
